# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('serial', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
