# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20170418_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='serial',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
