# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20170418_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
