# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_auto_20170420_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
