# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_auto_20170420_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
