# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20170420_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='hostname',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
